export type Dish = {
  id: string;
  name: string;
  nameHi?: string;
  category: "starters" | "tandoor" | "mains" | "biryani" | "desserts" | "drinks";
  region: string;
  description: string;
  price: number; // in CAD
  image: string;
  heat: 0 | 1 | 2 | 3; // 0..3 chillies
  veg: boolean;
  vegan?: boolean;
  gf?: boolean;
  signature?: boolean;
};

const u = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80`;

export const dishes: Dish[] = [
  {
    id: "papdi-chaat",
    name: "Lab Papdi Chaat",
    nameHi: "पपड़ी चाट",
    category: "starters",
    region: "Delhi",
    description: "Crisp wafers, whipped yogurt, tamarind, mint, and pomegranate.",
    price: 14,
    image: u("photo-1626132647523-66f5bf380027"),
    heat: 1,
    veg: true,
    signature: true,
  },
  {
    id: "kasundi-prawn",
    name: "Kasundi Prawn",
    nameHi: "कसुंडी झींगा",
    category: "starters",
    region: "Bengal",
    description: "Tiger prawn, mustard kasundi, charred lime.",
    price: 22,
    image: u("photo-1625944525533-473f1a3d54e7"),
    heat: 2,
    veg: false,
    gf: true,
  },
  {
    id: "tandoori-cauliflower",
    name: "Tandoori Cauliflower",
    nameHi: "तंदूरी फूलगोभी",
    category: "tandoor",
    region: "Punjab",
    description: "Whole roasted cauliflower, fenugreek butter, smoked yogurt.",
    price: 19,
    image: u("photo-1599487488170-d11ec9c172f0"),
    heat: 1,
    veg: true,
    gf: true,
    signature: true,
  },
  {
    id: "lamb-seekh",
    name: "Lamb Seekh",
    nameHi: "लैंब सीख",
    category: "tandoor",
    region: "Lucknow",
    description: "Hand-minced lamb, green cardamom, mint chutney.",
    price: 24,
    image: u("photo-1633577418728-9c19a4b32ac3"),
    heat: 2,
    veg: false,
    gf: true,
  },
  {
    id: "butter-chicken",
    name: "Lab Butter Chicken",
    nameHi: "बटर चिकन",
    category: "mains",
    region: "Delhi",
    description: "48-hour marinade, charred tomato cream, kasoori methi.",
    price: 28,
    image: u("photo-1603894584373-5ac82b2ae398"),
    heat: 1,
    veg: false,
    signature: true,
  },
  {
    id: "dal-makhani",
    name: "Black Dal",
    nameHi: "दाल मखनी",
    category: "mains",
    region: "Punjab",
    description: "Slow-cooked 36 hours, smoked butter, cream.",
    price: 22,
    image: u("photo-1585937421612-70a008356fbe"),
    heat: 0,
    veg: true,
    gf: true,
    signature: true,
  },
  {
    id: "goan-fish",
    name: "Goan Fish Curry",
    nameHi: "गोवा फिश करी",
    category: "mains",
    region: "Goa",
    description: "Day-boat catch, coconut, kokum, curry leaf.",
    price: 32,
    image: u("photo-1565557623262-b51c2513a641"),
    heat: 3,
    veg: false,
    gf: true,
  },
  {
    id: "hyderabadi-biryani",
    name: "Hyderabadi Biryani",
    nameHi: "हैदराबादी बिरयानी",
    category: "biryani",
    region: "Hyderabad",
    description: "Aged basmati, saffron, slow-cooked under dough seal.",
    price: 30,
    image: u("photo-1603133872878-684f208fb84b"),
    heat: 2,
    veg: false,
    signature: true,
  },
  {
    id: "veg-biryani",
    name: "Garden Biryani",
    nameHi: "सब्ज़ी बिरयानी",
    category: "biryani",
    region: "Awadh",
    description: "Heirloom vegetables, fried shallot, raita.",
    price: 24,
    image: u("photo-1589302168068-964664d93dc0"),
    heat: 1,
    veg: true,
  },
  {
    id: "rasmalai",
    name: "Saffron Rasmalai",
    nameHi: "रसमलाई",
    category: "desserts",
    region: "Bengal",
    description: "Cardamom milk, pistachio dust, edible gold.",
    price: 14,
    image: u("photo-1600891964599-f61ba0e24092"),
    heat: 0,
    veg: true,
    gf: true,
  },
  {
    id: "kulfi",
    name: "Mango Kulfi",
    nameHi: "कुल्फी",
    category: "desserts",
    region: "North India",
    description: "Alphonso, sea salt, toasted almond.",
    price: 12,
    image: u("photo-1590080875515-8a3a8dc5735e"),
    heat: 0,
    veg: true,
    gf: true,
  },
  {
    id: "masala-old-fashioned",
    name: "Masala Old Fashioned",
    category: "drinks",
    region: "House",
    description: "Bourbon, garam masala bitters, jaggery.",
    price: 18,
    image: u("photo-1551024709-8f23befc6f87"),
    heat: 0,
    veg: true,
    vegan: true,
    gf: true,
  },
  {
    id: "kashmiri-spritz",
    name: "Kashmiri Spritz",
    category: "drinks",
    region: "House",
    description: "Saffron gin, prosecco, rose, cucumber.",
    price: 17,
    image: u("photo-1514362545857-3bc16c4c7d1b"),
    heat: 0,
    veg: true,
    vegan: true,
    gf: true,
  },
];

export const signatureDishes = dishes.filter((d) => d.signature);
